export const appURL='https://sigs-studio.flowy-mouse-8040.chatgpt.site/app-Sigs.html';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const events={
 recovery:{subject:'SIGS Studio · Recuperar palavra-passe',title:'Recupera o acesso ao SIGS',copy:'Recebemos um pedido para recuperar a palavra-passe da tua conta. Usa o botão abaixo para escolher uma nova.',cta:'Definir nova palavra-passe',auth:true},
 invite:{subject:'SIGS Studio · O teu convite está pronto',title:'Bem-vindo ao SIGS Studio',copy:'Foste convidado para trabalhar no SIGS. Aceita o convite e define a tua palavra-passe para começar.',cta:'Aceitar convite',auth:true},
 confirmation:{subject:'SIGS Studio · Confirmar endereço de email',title:'Confirma o teu email',copy:'Confirma este endereço para concluir a ativação da tua conta.',cta:'Confirmar email',auth:true},
 magic_link:{subject:'SIGS Studio · O teu acesso seguro',title:'Entra no teu espaço de trabalho',copy:'Usa este link para entrar na tua conta. O link é pessoal e só pode ser utilizado uma vez.',cta:'Entrar no SIGS',auth:true},
 email_change:{subject:'SIGS Studio · Confirmar alteração de email',title:'Confirma o novo endereço',copy:'Foi pedida uma alteração do endereço de email da tua conta. Confirma a alteração no botão abaixo.',cta:'Confirmar alteração',auth:true},
 reauthentication:{subject:'SIGS Studio · Código de verificação',title:'Confirma a tua identidade',copy:'Introduz este código no SIGS para concluir a operação:',code:true,auth:true},
 password_changed_notification:{subject:'SIGS Studio · Palavra-passe alterada',title:'A tua palavra-passe foi alterada',copy:'A palavra-passe da tua conta SIGS foi alterada. Se não foste tu, recupera o acesso e contacta o administrador da tua empresa.',cta:'Abrir SIGS',security:true},
 email_changed_notification:{subject:'SIGS Studio · Endereço de email alterado',title:'O email da tua conta foi alterado',copy:'O endereço de email associado à tua conta foi alterado. Se não reconheces esta operação, contacta o administrador da tua empresa.',cta:'Abrir SIGS',security:true},
 welcome:{subject:'SIGS Studio · O teu espaço de trabalho está pronto',title:'Da planta à proposta, num só lugar',copy:'A tua conta foi associada à empresa. Entra no SIGS, carrega uma planta ou abre o mapa e começa a projetar.',cta:'Começar projeto'},
 license_activated:{subject:'SIGS Studio · Licença ativada',title:'A tua licença está ativa',copy:'A tua empresa já pode usar o SIGS com o plano indicado abaixo.',cta:'Abrir espaço de trabalho'},
 license_renewed:{subject:'SIGS Studio · Licença renovada',title:'Mais tempo para os teus projetos',copy:'A licença da tua empresa foi renovada. Consulta abaixo a nova data de validade.',cta:'Continuar a trabalhar'},
 license_expiring:{subject:'SIGS Studio · A tua licença está a terminar',title:'Está na altura de renovar',copy:'A licença da tua empresa aproxima-se do fim. Contacta o responsável pela plataforma para tratar da renovação e manter o acesso.',cta:'Consultar licença'},
 license_expired:{subject:'SIGS Studio · Licença expirada',title:'A validade da licença terminou',copy:'A validade da licença terminou. Contacta o responsável pela plataforma para renovar e recuperar o acesso.',cta:'Consultar conta'},
 license_suspended:{subject:'SIGS Studio · Licença suspensa',title:'A licença foi suspensa',copy:'A licença da tua empresa foi suspensa. Contacta o responsável pela plataforma para esclarecer a situação.',cta:'Consultar conta'},
 license_reactivated:{subject:'SIGS Studio · Licença reativada',title:'Podes voltar aos teus projetos',copy:'A licença da tua empresa foi reativada. Consulta os dados abaixo e entra no SIGS.',cta:'Abrir SIGS'}
};
function link(value){const u=new URL(value);if(u.protocol!=='https:')throw Error('Email links require HTTPS');return u.href;}
export function renderEmail(kind,data={},options={}){
 const event=events[kind];if(!event)throw Error('Unknown email event');const auth=options.authTemplate===true;
 const url=auth?(event.security?'{{ .SiteURL }}':'{{ .ConfirmationURL }}'):link(options.appURL||appURL);
 const rows=[];if(!auth){for(const [key,label] of [['company','Empresa'],['plan','Plano'],['billing','Periodicidade'],['expires','Válida até'],['days','Dias restantes'],['maxProjects','Projetos'],['maxItems','Equipamentos por projeto']])if(data[key]!==undefined&&data[key]!==null&&data[key]!=='')rows.push(`<tr><td style="padding:8px 0;color:#66758a;font-size:13px">${label}</td><td style="padding:8px 0;text-align:right;color:#17273e;font-size:13px;font-weight:bold">${esc(data[key])}</td></tr>`);}
 const details=rows.length?`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f6fb;border-radius:12px;margin:20px 0"><tr><td style="padding:12px 18px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${rows.join('')}</table></td></tr></table>`:'';
 const code=event.code?`<p style="font-size:30px;letter-spacing:8px;font-weight:bold;color:#3869e8">${auth?'{{ .Token }}':'123456'}</p>`:'';
 const cta=event.cta?`<table role="presentation" cellspacing="0" cellpadding="0" style="margin:24px 0"><tr><td bgcolor="#3869e8" style="border-radius:9px"><a href="${esc(url)}" style="display:inline-block;padding:14px 22px;font:700 14px Arial,sans-serif;color:#ffffff;text-decoration:none">${event.cta}</a></td></tr></table>`:'';
 const warning=event.auth?'Se não pediste esta operação, ignora este email. Nunca partilhes o link ou o código de acesso.':'Este email refere-se à conta e à licença da tua empresa no SIGS.';
 const fallback=event.cta?`<p style="font-size:11px;color:#7d899b;line-height:1.6;word-break:break-all">Se o botão não funcionar, copia este endereço:<br><a href="${esc(url)}" style="color:#3869e8">${esc(url)}</a></p>`:'';
 const html=`<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(event.subject)}</title></head><body style="margin:0;padding:0;background:#edf2f8;font-family:Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden">${esc(event.copy)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="560" cellpadding="0" cellspacing="0" style="width:100%;max-width:560px;background:#ffffff;border:1px solid #dfe7f2;border-radius:18px"><tr><td style="padding:26px 30px;background:#15243b;border-radius:18px 18px 0 0"><img src="https://sigs-studio.flowy-mouse-8040.chatgpt.site/assets/brand/sigs-studio-logo.png" width="200" height="100" alt="SIGS Studio" style="display:block;width:200px;max-width:100%;height:auto;background:#ffffff;border-radius:9px;border:0"><p style="margin:8px 0 0;font-size:11px;color:#b5c7e5">Segurança bem projetada.</p></td></tr><tr><td style="padding:30px"><p style="margin:0 0 12px;font-size:11px;letter-spacing:2px;color:#3869e8">O TEU ESPAÇO DE PROJETO</p><h1 style="margin:0 0 18px;font-size:27px;line-height:1.25;color:#17273e">${esc(event.title)}</h1><p style="font-size:14px;line-height:1.8;color:#526277">${esc(event.copy)}</p>${auth?'<p style="font-size:12px;color:#66758a">Conta: {{ .Email }}</p>':''}${details}${code}${cta}<p style="font-size:12px;line-height:1.7;color:#66758a">${warning}</p>${fallback}</td></tr><tr><td style="padding:20px 30px;border-top:1px solid #e7edf5;font-size:11px;line-height:1.7;color:#7d899b">by SIGS Studio · Segurança bem projetada.<br>Email automático. Para apoio, contacta o administrador da tua empresa.</td></tr></table></td></tr></table></body></html>`;
 return {subject:event.subject,html,text:['SIGS Studio · Segurança bem projetada.',event.title,event.copy,...rows.map((_,i)=>''),...Object.entries(data).filter(([k])=>['company','plan','billing','expires','days','maxProjects','maxItems'].includes(k)).map(([k,v])=>`${k}: ${v}`),event.code?(auth?'{{ .Token }}':'123456'):url,warning].filter(Boolean).join('\n\n')};
}
