const assert=require('assert'),fs=require('fs'),vm=require('vm');
const {JSDOM}=require('jsdom');
const M=require('../assets/js/accessory-model-v10.js');
const cams=[{type:'thermal_bi'},{type:'dome'}];
const suggest=(watts,va,units=9)=>M.suggest(cams,{ups:{load:watts/1.25,watts,va,minutes:15},rackUnits:units});
assert.equal(suggest(360,600).find(x=>x.key==='system-ups').ref,'UPS600VA-6');
assert.equal(suggest(361,600).find(x=>x.key==='system-ups').ref,'UPS1000VA-ON-2-RACK');
assert.equal(suggest(350,1001).find(x=>x.key==='system-ups').ref,'UPS1500VA-ON-2-RACK');
assert.equal(suggest(1400,1600).find(x=>x.key==='system-ups').ref,'UPS2000VA-ON-2-RACK');
assert.equal(suggest(1801,1900).find(x=>x.key==='system-ups').ref,'GEN-UPS-CCTV');
assert.equal(suggest(350,500,10).find(x=>x.key==='system-rack').ref,'RACK-12UN');
assert.equal(suggest(350,500,13).find(x=>x.key==='system-rack').ref,'GEN-RACK-CCTV');
assert(suggest(361,600).some(x=>x.ref==='UPS-RACK-KIT'));
assert(!suggest(360,600).some(x=>x.ref==='UPS-RACK-KIT'));
assert.equal(suggest(360,600).find(x=>x.key==='network-termination').qty,4);
assert.equal(suggest(360,600).find(x=>x.key==='network-termination').name,'Fichas de RJ45');
assert(!M.suggest([{type:'pir_indoor'}]).some(x=>x.key==='system-ups'));
let extras=[];M.accept(extras,suggest(360,600).find(x=>x.key==='system-ups'));M.sync(extras,suggest(900,1000));assert.equal(extras[0].ref,'UPS600VA-6','Previously accepted reference remains a user choice');
const dom=new JSDOM('<div id="m-bom"><div id="v8-totals"></div></div>',{runScripts:'outside-only'}),w=dom.window;
Object.assign(w,{SIGSAccessoryModel:M,SIGS_COMMERCIAL:{extras:[]},S:{},FLOORS:[{placed:[{libId:'cam'}]}],gD:()=>cams[0],SIGSEngineering:{snapshot:()=>({ups:{load:300,watts:375,va:650,minutes:15}})}});
w.eval(fs.readFileSync('assets/js/proposal-v10.js','utf8'));w.sigsV10EnhanceBudget();
const rows=[...w.document.querySelectorAll('.v10-suggestion')];
assert(rows.some(r=>r.textContent.includes('UPS1000VA-ON-2-RACK')));
assert(rows.some(r=>r.textContent.includes('RACK-9UN-6D')));
const link=w.document.querySelector('a');assert(link.href.startsWith('https://www.visiotechsecurity.com/'));assert.equal(link.rel,'noopener noreferrer');
w.sigsV6MarkDirty=()=>{};w.openBOM=()=>{};
rows.find(r=>r.textContent.includes('UPS1000VA-ON-2-RACK')).querySelector('button').click();
assert.equal(w.SIGS_COMMERCIAL.extras[0].ref,'UPS1000VA-ON-2-RACK');
console.log('PASS: UPS W/VA boundaries, thermal cameras, rack capacity, kit, preserved accepted model and actual budget UI/add action');
