const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module'),{JSDOM}=require('jsdom');
const root=require('node:path').resolve(__dirname,'..'),read=p=>fs.readFileSync(root+'/'+p,'utf8');
const flush=()=>new Promise(r=>setTimeout(r,0));
(async()=>{
// Real browser handlers: all roles can open own account; only Super Admin sees audit buttons.
for(const role of ['SUPER_ADMIN','ADMIN','SALES']){
 const dom=new JSDOM('<button id="w12-portal-launch">SIGS WORKSPACE</button>',{url:'https://www.sigs-studio.pt/app-Sigs.html',runScripts:'outside-only'}),w=dom.window,calls=[];
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.setInterval=()=>1;w.CLOUD={user:{id:'u',role,email:'owner@example.test'},access:'token'};w.fetch=async(url,o)=>{calls.push({url,...o});return {ok:true,json:async()=>({ok:true,rows:[],users:[],presence:[]})};};w.eval(read('assets/js/activity-v42.js'));
 assert(w.document.body.textContent.includes('A minha conta'));assert.equal(w.document.body.textContent.includes('Acessos e online'),role==='SUPER_ADMIN');
 w.SIGSActivity.password();const form=w.document.querySelector('form');form.elements.current.value='old-password';form.elements.password.value='new-password';form.elements.confirm.value='mismatch';form.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert(form.textContent.includes('não coincidem'));
 form.elements.confirm.value='new-password';form.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();const change=calls.find(c=>c.url.endsWith('/auth/v1/user'));assert(change);assert.equal(change.method,'PUT');assert.equal(JSON.parse(change.body).current_password,'old-password');assert(!JSON.parse(change.body).user_id);assert(form.textContent.includes('sucesso'));dom.window.close();
}
// Public views use a separate minimal script; private pages do not load it.
for(const f of ['index.html','acesso.html','registo.html','privacidade.html'])assert(read(f).includes('pageviews-v57.js'));
for(const f of ['app-Sigs.html','proposta.html'])assert(!read(f).includes('pageviews-v57.js'));
// Real Edge handler: public consent required, admin authorization enforced, page allowlist.
let handler,role='ADMIN',dbCalls=[];
const context={Deno:{env:{get:k=>k==='SUPABASE_URL'?'https://backend.test':'service-test'},serve:f=>handler=f},Request,Response,Headers,AbortSignal,Set,Map,Date,JSON,atob,crypto:globalThis.crypto,fetch:async(url,opts)=>{dbCalls.push({url,opts});if(opts?.method==='HEAD')return new Response(null,{headers:{'content-range':'0-0/0'}});if(url.endsWith('/auth/v1/user'))return Response.json({id:'u'});if(url.includes('/profiles?'))return Response.json([{id:'u',role,active:true}]);return Response.json([]);}};
vm.createContext(context);vm.runInContext(stripTypeScriptTypes(read('supabase/functions/sigs-activity/index.ts')),context);
const request=(body,auth)=>handler(new Request('https://backend.test/functions/v1/sigs-activity',{method:'POST',headers:{origin:'https://www.sigs-studio.pt','Content-Type':'application/json',...(auth?{authorization:'Bearer invalid'}:{})},body:JSON.stringify(body)}));
assert.equal((await request({action:'dashboard'})).status,401);assert.equal((await request({action:'dashboard'},true)).status,403);role='SUPER_ADMIN';assert.equal((await request({action:'dashboard'},true)).status,200);assert.equal((await request({action:'visit',page:'/'})).status,201);assert.equal((await request({action:'visit',page:'/?token=secret'})).status,400);assert.equal((await request({action:'visits'})).status,401);role='ADMIN';assert.equal((await request({action:'visits'},true)).status,403);role='SUPER_ADMIN';assert.equal((await request({action:'visits',days:7},true)).status,200);
const jwt='header.'+Buffer.from(JSON.stringify({session_id:'00000000-0000-4000-8000-000000000001'})).toString('base64url')+'.signature';
const heartbeat=await handler(new Request('https://backend.test/functions/v1/sigs-activity',{method:'POST',headers:{authorization:'Bearer '+jwt,'Content-Type':'application/json'},body:JSON.stringify({action:'heartbeat',page:'/app-Sigs.html',tab:'00000000-0000-4000-8000-000000000002',online:true})}));assert.equal(heartbeat.status,200);assert(dbCalls.some(c=>c.url.includes('on_conflict=session_id,tab_id')));assert(dbCalls.some(c=>c.url.includes('sigs_access_events?on_conflict=session_id')));
const write=dbCalls.find(c=>c.url.endsWith('/sigs_visits')&&c.opts.method==='POST');assert(write);assert.deepEqual(Object.keys(JSON.parse(write.opts.body)).sort(),['city','consent_version','country','ip','page','region','visitor_id']);assert.equal(JSON.parse(write.opts.body).consent_version,'ip-pageview-v58');
const html=read('index.html'),schema=JSON.parse(html.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)[1]);assert.equal(schema['@graph'].find(o=>o['@type']==='SoftwareApplication').offers.length,4);assert(html.includes('rel="canonical" href="https://www.sigs-studio.pt/"'));assert(read('robots.txt').includes('/sitemap.xml'));for(const f of ['app-Sigs.html','acesso.html','proposta.html','registo.html'])assert(/name="robots" content="noindex,/.test(read(f)));assert(read('scripts/build-static.cjs').includes("'sitemap.xml'"));
console.log('PASS: own password for all roles, minimal public views, protected visitor history and access 401/403, SEO files.');
})().catch(e=>{console.error(e);process.exitCode=1;});
