const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module'),{JSDOM}=require('jsdom');
const original=fs.readFileSync('supabase/functions/sigs-admin/index.ts','utf8');
const source=stripTypeScriptTypes(original.replace(/^import .*;\n/gm,''));
async function server(body,{role='SUPER_ADMIN',company=true,fail=false,jwt=true}={}){
 const calls=[];let handler;
 function chain(table){const q={};for(const method of ['select','eq','insert','update','upsert','order','lte','limit'])q[method]=(...args)=>{calls.push([table,method,...args]);return q;};const value=()=>({data:table==='profiles'?{id:'caller',role,active:true}:table==='company_members'?{company_id:'co',role:'ADMIN',active:true}:table==='companies'?(company?{id:'co'}:null):null,error:null});q.single=q.maybeSingle=async()=>value();q.then=(ok,bad)=>Promise.resolve(value()).then(ok,bad);return q;}
 const client={from:chain,auth:{getUser:async()=>({data:{user:{id:'caller'}}}),admin:{inviteUserByEmail:async(...args)=>{calls.push(['invite',...args]);return fail?{error:new Error('Mail failed')}:{data:{user:{id:'invited'}}};},createUser:async()=>{throw Error('Must not set a customer password');}}}};
 vm.runInNewContext(source,{Deno:{env:{get:()=> 'test'},serve:fn=>handler=fn},createClient:()=>client,Request,Response,crypto:globalThis.crypto,console:{error(){}}});
 const response=await handler(new Request('https://edge.test',{method:'POST',headers:jwt?{Authorization:'Bearer caller-token'}:{},body:JSON.stringify(body)}));return {status:response.status,body:await response.json(),calls};
}
const invitation={action:'invite_user',company_id:'co',role:'ADMIN',email:'client@example.com',name:'Cliente'};
const flush=()=>new Promise(r=>setImmediate(r));
(async()=>{
 for(const body of [invitation,{...invitation,action:'create_admin_with_password',password:'ignored-password',role:'SALES',redirect_to:'https://evil.test'}]){
  const r=await server(body);assert.equal(r.status,200);assert.equal(r.body.activation_email_sent,true);const invite=r.calls.find(c=>c[0]==='invite');assert.equal(invite[1],'client@example.com');assert.equal(invite[2].redirectTo,'https://www.sigs-studio.pt/acesso.html');assert.equal(invite[2].password,undefined);const member=r.calls.find(c=>c[0]==='company_members'&&c[1]==='upsert');assert.equal(member[2].role,'ADMIN');assert.equal(member[2].user_id,'invited');
 }
 for(const [options,status] of [[{role:'ADMIN'},403],[{company:false},404],[{jwt:false},401],[{fail:true},500]]){const r=await server(invitation,options);assert.equal(r.status,status);assert(!r.calls.some(c=>c[0]==='company_members'&&c[1]==='upsert'));}
 assert.equal((await server({...invitation,email:'bad-email'})).status,400);
 const dom=new JSDOM('<div id="license-body"></div>',{url:'https://www.sigs-studio.pt/app-Sigs.html',runScripts:'outside-only'}),w=dom.window,posts=[],messages=[];
 w.CLOUD={user:{id:'caller',role:'SUPER_ADMIN'},access:'token'};w._esc=v=>String(v);w.startModule=()=>{};w.notify=v=>messages.push(v);
 w.fetch=async(url,options={})=>{if(url.includes('/functions/v1/')){const body=JSON.parse(options.body);posts.push(body);return {ok:true,text:async()=>JSON.stringify(body.action==='create_company'?{company:{id:'co'}}:body.action==='issue_license'?{license:{id:'lic'}}:{activation_email_sent:true})};}return {ok:true,text:async()=> '[]'};};
 vm.runInContext(fs.readFileSync('assets/js/block-04.js','utf8'),dom.getInternalVMContext());w.renderLicenseCenter();await flush();assert(!w.document.getElementById('lic-admin-password'));for(const [id,value] of [['lic-company','Cliente Lda'],['lic-admin-name','Cliente'],['lic-admin-email','client@example.com']])w.document.getElementById(id).value=value;w.licCreateLicense();await flush();await flush();assert.equal(posts.at(-1).action,'invite_user');assert.equal(posts.at(-1).role,'ADMIN');assert(!posts.some(p=>Object.hasOwn(p,'password')));assert(messages.some(m=>m.includes('Email de ativação enviado')));dom.window.close();
 const html=fs.readFileSync('acesso.html','utf8');const access=new JSDOM(html,{url:'https://www.sigs-studio.pt/acesso.html#type=invite&access_token=invite-token',runScripts:'outside-only'}),a=access.window,requests=[];
 a.fetch=async(url,options)=>{requests.push({url,...options});return {ok:true,json:async()=>({id:'client'})};};vm.runInContext(fs.readFileSync('assets/js/email-access-v15.js','utf8'),access.getInternalVMContext());await flush();assert(a.document.getElementById('email-field').hidden);assert(!a.document.getElementById('password-fields').hidden);assert.equal(a.location.hash,'');
 const form=a.document.getElementById('access-form');a.document.getElementById('access-password').value='Initial-test-123!';a.document.getElementById('access-repeat').value='mismatch';form.dispatchEvent(new a.Event('submit',{cancelable:true}));await flush();assert(!requests.some(r=>r.method==='PUT'));
 a.document.getElementById('access-repeat').value='Initial-test-123!';form.dispatchEvent(new a.Event('submit',{cancelable:true}));await flush();assert.equal(JSON.parse(requests.find(r=>r.method==='PUT').body).password,'Initial-test-123!');assert.equal(requests.find(r=>r.method==='PUT').headers.Authorization,'Bearer invite-token');assert(requests.some(r=>r.url.includes('logout?scope=global')));assert.equal(a.document.getElementById('access-title').textContent,'Conta ativada');assert.equal(a.document.getElementById('access-password').value,'');access.window.close();
 console.log('PASS: authorised admin invitations, cached-client alias, server-controlled redirect, mail/validation failures, no supplied password, client wizard and initial-password activation flow.');
})().catch(e=>{console.error(e);process.exitCode=1;});
