const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const m=require('../assets/js/commercial-model-v8.js');
let c=m.defaults();c.prices.X={cost:100,sale:null};c.margin=25;c.marginMode='margin';let q=m.calculate([{ref:'X',qty:2}],c);assert.equal(q.sub,266.66);assert.equal(q.total,327.99);
c.discount=10;c.prices.X.sale=150;c.laborHours=2;c.laborSale=40;c.laborCost=20;q=m.calculate([{ref:'X',qty:2}],c);assert.equal(q.sub,342);assert.equal(q.cost,240);assert.equal(q.total,420.66);
c.prices.X.sale=0;assert.equal(m.calculate([{ref:'X',qty:2}],c).lines[0].sale,0);
const ctx={console,Math,Date,Map,Number,JSON,setTimeout:fn=>fn(),setInterval:()=>{},document:{readyState:'complete',getElementById:()=>null},SIGSCommercialModel:m,MOD:'cctv',S:{placed:[{libId:'cam',mp:4}],scale:{ok:false}},FLOOR_CUR:0,FLOORS:[{placed:[],scale:{ok:false}},{placed:[{libId:'cam',mp:4}],scale:{ok:false}}],NVR_POS:null,SIGS_PRICES:{},BUDGET:{prices:{},cablePrice:0.8},BITRATE_TABLE:{ultra265b:{4:4},h265:{4:4}},gD:id=>({id,model:'CAM-1',name:'Camera',type:'dome'}),saveCurrentFloor(){ctx.FLOORS[0].placed=ctx.S.placed;},calcStorage:()=>({gb:13000}),suggestNVR:()=>[{name:'NVR-1',hdd:2}],calcPoE:()=>({suggested:[{name:'SW-1'}]}),nearestHDD:()=>12,sigsHddCatalogRef:tb=>'HDD-'+tb,_buildProjectData:()=>({placed:[],lib:[],floors:[]}),_restoreProjectData:()=>{},startModule:()=>{},notify:()=>{}};
ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/js/commercial-v8.js'),'utf8'),ctx);
let result=ctx.sigsV8Quote();assert.equal(result.lines.find(r=>r.ref==='CAM-1').qty,2);assert.equal(result.lines.find(r=>r.ref==='HDD-12').qty,3);assert.equal(result.lines.find(r=>r.type==='cabo').qty,30);assert(result.warnings.some(w=>w.includes('baias')));
ctx.SIGS_COMMERCIAL.prices['CAM-1']={cost:100,sale:150};ctx.SIGS_COMMERCIAL.discount=10;ctx.SIGS_COMMERCIAL.client='Cliente A';let saved=ctx._buildProjectData();assert.equal(saved.commercial.client,'Cliente A');ctx._restoreProjectData(saved);assert.equal(ctx.SIGS_COMMERCIAL.prices['CAM-1'].sale,150);assert.equal(ctx.SIGS_COMMERCIAL.discount,10);
ctx.SIGSSiteGeometry=require('../assets/js/site-geometry-model-v28.js');
ctx.S.placed[0]=Object.assign(ctx.S.placed[0],{x:0,y:0,instHeight:3,cableAnchor:'start',cableRoute:[{x:0,y:0},{x:30,y:0},{x:30,y:40}]});
ctx.FLOORS[0].scale={ok:true,ppm:10};ctx.FLOORS[0].cabling={slackMeters:2,slackPercent:10};
ctx.FLOORS[1].placed[0]=Object.assign(ctx.FLOORS[1].placed[0],{x:0,y:0,instHeight:3,cableAnchor:'start',cableRoute:[{x:0,y:0},{x:30,y:0},{x:30,y:40}]});
ctx.FLOORS[1].scale={ok:true,ppm:5};ctx.FLOORS[1].cabling={slackMeters:1,slackPercent:20};
assert.equal(ctx.sigsV8Quote().lines.find(r=>r.ref==='Cabo UTP Cat6').qty,35);
ctx.FLOORS[0].cabling={slackMeters:5,slackPercent:0};assert.equal(ctx.sigsV8Quote().lines.find(r=>r.ref==='Cabo UTP Cat6').qty,37);
ctx.S.placed=[];ctx.FLOORS[1].placed=[];assert.equal(ctx.sigsV8Quote().lines.length,0);ctx._restoreProjectData({placed:[],lib:[]});assert.equal(ctx.SIGS_COMMERCIAL.client,'');assert.equal(Object.keys(ctx.SIGS_COMMERCIAL.prices).length,0);
console.log('PASS: pricing, tax, labor, multi-floor quantities, disk counts, warnings, serialization, restore, deletion and project isolation');
