const assert=require('node:assert/strict'),fs=require('fs'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<body><div id="lp"><div id="lib-search-wrap"><input id="lib-search"></div><div id="dlist"></div></div><aside class="studio-rail"><nav class="sigs-v5-nav"></nav><div class="studio-rail-foot"></div></aside></body>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
Object.defineProperty(w.document,'readyState',{value:'complete'});w.setTimeout=(fn,ms)=>{if(ms===900)fn();return 1;};w.setInterval=()=>1;w.requestAnimationFrame=fn=>fn();w.resize=()=>{};w.S={lib:[]};w.MOD='cctv';w.sLib=()=>{};w.CLOUD={projectId:'current-only',projectName:'Armazém <A>',user:{id:'u'},access:'test'};
let queries=[];w._sigsSbCfg=()=>({url:'https://example.test'});w._sigsSbHeaders=()=>({});w._sigsSbJson=async url=>{queries.push(url);return [{id:'a2',version_no:4,reason:'AUTO',created_at:'2026-10-09T23:20:00Z'},{id:'m1',version_no:3,reason:'MANUAL',created_at:'2026-10-09T23:15:00Z'},{id:'a1',version_no:2,reason:'AUTO',created_at:'2026-10-09T23:10:00Z'}];};w.notify=()=>{};
w.eval(fs.readFileSync('assets/js/projects-v6.js','utf8'));w.eval(fs.readFileSync('assets/js/sidebar-v13.js','utf8'));
(async()=>{w.SIGS_V6.dirty=true;w.document.getElementById('s13-load-project').click();await new Promise(r=>setImmediate(r));
assert.equal(queries.length,1);assert(queries[0].includes('project_id=eq.current-only'));const panel=w.document.getElementById('sigs-v6-versions');assert(panel);assert(panel.textContent.includes('Armazém <A>'));assert.equal(panel.querySelectorAll('.sigs-v6-version').length,3);assert(w.SIGS_V6.dirty);
const filter=panel.querySelector('select');filter.value='MANUAL';filter.dispatchEvent(new w.Event('change'));assert.equal(panel.querySelectorAll('.sigs-v6-version').length,1);assert(panel.textContent.includes('Gravação manual'));filter.value='AUTO';filter.dispatchEvent(new w.Event('change'));assert.equal(panel.querySelectorAll('.sigs-v6-version').length,2);
w.confirm=()=>false;panel.querySelector('[data-restore]').click();assert.equal(queries.length,1,'Cancellation sends no restore request');assert(w.SIGS_V6.dirty);dom.window.close();console.log('PASS: actual sidebar opens current-only history, shows manual and two automatic versions, filters, escapes project name and preserves edits until restore');})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
