const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../assets/js/disk-model-v64.js');
const cam={id:1,name:'Entrada',resId:'2mp',codecId:'uv_ultra265',fps:25,qty:1};
const settings={days:1,hours:24,overhead:0,reserve:0,margin:0};
assert.equal(M.automatic(cam),2);
assert.equal(M.automatic({...cam,codecId:'uv_h264'}),4);
assert.equal(M.automatic({...cam,resId:'6mp'}),6);
assert.equal(M.automatic({...cam,fps:15}),1.2);
assert.equal(M.automatic({...cam,ucodeSaving:50}),1);
assert(Math.abs(M.automatic({...cam,ucodeSaving:90})-.2)<1e-12);
assert.equal(M.automatic({...cam,codecId:'uv_h265',ucodeSaving:90}),2);
assert.equal(M.dimension([cam],settings).bytes,21600000000);
assert.equal(M.dimension([{...cam,qty:4}],settings).bytes,86400000000);
assert.equal(M.group(cam,{...settings,mode:'event',eventPercent:0}).bytes,0);
assert.equal(M.group(cam,{...settings,mode:'event',eventPercent:25,hours:12}).bytes,2700000000);
let g=M.group(cam,{...settings,motion:true,motionPercent:25,motionFactor:4});
assert.equal(g.mean,3.5);assert.equal(g.peak,8);
g=M.group(cam,{...settings,motion:true,motionPercent:0,motionFactor:4});assert.equal(g.mean,2);assert.equal(g.peak,2);
g=M.group({...cam,bitrate:1,ucodeSaving:90,fps:1,peakMbps:4},{...settings,motion:true,motionPercent:100,motionFactor:4});
assert.equal(g.mean,1);assert.equal(g.peak,4);assert.equal(g.bytes,10800000000);
let d=M.dimension([{...cam,bitrate:1}],{...settings,overhead:5,reserve:25,margin:20,installedTB:.01701});
assert.equal(d.requiredBytes,17010000000);assert.equal(d.retentionDays,1);assert.equal(d.installedEnough,true);
assert.equal(M.group({...cam,qty:0},settings).qty,1);
const {JSDOM}=require('jsdom'),dom=new JSDOM(fs.readFileSync(require.resolve('../app-Sigs.html'),'utf8'));
let copied='';const e={document:dom.window.document,window:null,SIGSDiskModel:M,console,setTimeout(){},Math,Date,navigator:{clipboard:{writeText(t){copied=t;return Promise.resolve();}}},notify(){}};e.window=e;vm.createContext(e);
const raw=fs.readFileSync(require.resolve('../assets/js/block-03.js'),'utf8');vm.runInContext(raw.slice(raw.indexOf('var DC_BRANDS ='),raw.indexOf('// ── Show / Hide')),e);e.dcDrawGauge=()=>{};
e._dcBrand='uniview';e._dcCams=[{...cam}];const doc=e.document;
for(const [id,value] of Object.entries({'dc-days':1,'dc-hours':24,'dc-margin':0,'dc-overhead':0,'dc-raid':0,'dc-record-mode':'continuous','dc-installed-tb':.0432}))doc.getElementById(id).value=value;
e.dcRebuildCams();e.dcCalc();assert(doc.getElementById('dc-s-raw').textContent.includes('21.6 GB'));assert(doc.getElementById('dc-installed-result').textContent.includes('2.0 dias'));
assert.equal(e.DC_BRANDS.uniview.codecs.length,3);assert(!e.dcMakeCodecOpts().includes('uv_ultra265max'));assert(e.dcMakeResOpts().includes('6mp'));
for(const brand of Object.keys(e.DC_BRANDS)){const img=doc.querySelector('#dc-blogo-'+brand+' img');assert(img);assert(fs.existsSync(require('node:path').join(__dirname,'..',img.getAttribute('src'))));}
e._dcMotionOn=true;doc.getElementById('dc-motion-pct').value=25;doc.getElementById('dc-motion-factor').value=4;e.dcCalc();assert(doc.getElementById('dc-s-bw').textContent.startsWith('8.0 Mbps'));assert(doc.getElementById('dc-s-raw').textContent.includes('37.8 GB'));
e.dcExportTxt();assert(copied.includes('3.50 Mbps médios · pico 8.00 Mbps'));
e._dcCamBitrate(1,'1');e._dcCamSet(1,'ucodeSaving',90);assert(doc.getElementById('dc-s-raw').textContent.includes('10.8 GB'));assert(doc.getElementById('dc-s-bw').textContent.includes('confirmar picos'));
e._dcCamSet(1,'peakMbps',5);assert(doc.getElementById('dc-s-bw').textContent.startsWith('5.0 Mbps'));
doc.getElementById('dc-record-mode').value='event';doc.getElementById('dc-event-pct').value=0;e.dcCalc();assert(doc.getElementById('dc-hero-num').textContent.includes('0 GB'));assert(doc.getElementById('dc-installed-result').textContent.includes('Sem gravação'));
e._dcCams.push({...cam,id:2,name:'<img src=x onerror=alert(1)>'});e.dcRebuildCams();e.dcCalc();assert(!doc.querySelector('#dc-group-bars img'));assert.equal(doc.querySelector('#dc-camcard-2 .dc-cam-name').value,e._dcCams[1].name);
console.log('PASS: calculator units, Ultra265 assumptions, measured bitrate, FPS, scene means/peaks, events, margins, retention, UI/export parity, safe names and brand assets.');
