import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {events,renderEmail} from '../supabase/functions/_shared/email-model.mjs';
for(const [kind,event] of Object.entries(events)){const m=renderEmail(kind,{company:'<img src=x onerror=bad>',plan:'Pro',maxProjects:50,maxItems:100},{authTemplate:!!(event.auth||event.security)});assert.ok(!m.html.includes('<img src=x'));assert.ok(m.html.includes('SIGS'));assert.ok(m.html.includes('https://www.sigs-studio.pt/assets/brand/sigs-studio-logo.png'));assert.ok(!m.html.includes('javascript:'));if(event.auth&&!event.code)assert.ok(m.html.includes('{{ .ConfirmationURL }}'));if(event.code)assert.ok(m.html.includes('{{ .Token }}'));assert.ok(m.subject.length<100);}
assert.ok(renderEmail('welcome').text.includes('https://www.sigs-studio.pt/app-Sigs.html'));
assert.throws(()=>renderEmail('missing'));assert.throws(()=>renderEmail('welcome',{}, {appURL:'javascript:alert(1)'}));
const source=fs.readFileSync(new URL('../assets/js/email-access-v15.js',import.meta.url),'utf8');
async function harness(hash='',responses=[]){const ids=['access-title','access-copy','access-form','access-email','email-field','password-fields','access-password','access-repeat','access-submit','access-status'];const nodes={};let submit,cleaned=false;const calls=[];for(const id of ids)nodes[id]={value:'',dataset:{},hidden:false,focus(){},addEventListener(e,f){if(id==='access-form')submit=f;}};const ctx={URL,URLSearchParams,location:{hash,pathname:'/Sigs/acesso.html',search:'',href:'https://flavavisio.github.io/Sigs/acesso.html'+hash},history:{replaceState(){cleaned=true;}},document:{getElementById:id=>nodes[id]},fetch:async(url,opts)=>{calls.push({url,opts});const reply=responses.shift()||{ok:true};return {ok:reply.ok,status:reply.status||200,json:async()=>reply.body||{}};}};vm.runInNewContext(source,ctx);await new Promise(r=>setImmediate(r));return {nodes,calls,get cleaned(){return cleaned;},submit:()=>submit({preventDefault(){}})};}
const recover=await harness();recover.nodes['access-email'].value='person@example.com';await recover.submit();assert.ok(recover.calls[0].url.includes('/recover?redirect_to=https%3A%2F%2Fflavavisio.github.io%2FSigs%2Facesso.html'));assert.deepEqual(JSON.parse(recover.calls[0].opts.body),{email:'person@example.com'});assert.ok(recover.nodes['access-status'].textContent.startsWith('Se este email'));assert.ok(!recover.calls[0].opts.headers.Authorization);
const reset=await harness('#type=recovery&access_token=secret&refresh_token=refresh');assert.ok(reset.cleaned);assert.equal(reset.calls[0].opts.headers.Authorization,'Bearer secret');assert.equal(reset.nodes['password-fields'].hidden,false);reset.nodes['access-password'].value='12345678';reset.nodes['access-repeat'].value='87654321';await reset.submit();assert.equal(reset.calls.length,1);reset.nodes['access-repeat'].value='12345678';await reset.submit();assert.equal(reset.calls[1].opts.method,'PUT');assert.ok(reset.calls[2].url.includes('logout?scope=global'));assert.equal(reset.nodes['access-password'].value,'');assert.equal(reset.nodes['access-form'].hidden,true);
const expired=await harness('#type=recovery&access_token=expired',[{ok:false,status:401}]);assert.ok(expired.cleaned);assert.ok(expired.nodes['access-status'].textContent.includes('expirou'));assert.equal(expired.nodes['access-email'].required,undefined);
const limited=await harness('',[{ok:false,status:429}]);limited.nodes['access-email'].value='person@example.com';await limited.submit();assert.ok(limited.nodes['access-status'].textContent.includes('Aguarda'));
const paid=renderEmail('license_activated',{reference:'SIGS-123',amount:'4,99 €',vat:'Não incluído',starts:'09/10/2026',expires:'09/11/2026',duration:'31 dias'});assert(paid.html.includes('4,99 €'));assert(paid.text.includes('Referência da licença: SIGS-123'));assert(paid.text.includes('Validade: 31 dias'));assert(paid.text.includes('IVA: Não incluído'));assert(renderEmail('license_requested').text.includes('aguarda aprovação'));
console.log('PASS: license value/validity/reference, templates, HTML escaping, safe URLs, reset/expired/rate-limited flows, hash removal, password confirmation and global sign-out.');
