import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {stripTypeScriptTypes} from 'node:module';import {renderEmail} from '../supabase/functions/_shared/email-model.mjs';
const raw=fs.readFileSync(new URL('../supabase/functions/sigs-email-worker/index.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');const source=stripTypeScriptTypes(raw);
function worker({configured=true,enabled=true,profile={role:'SUPER_ADMIN',active:true}}={}){let serve,sends=0;const calls=[];const settings={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'service-test-key',...(configured?{SMTP_HOST:'smtp.example.com',SMTP_PORT:'465',SMTP_USER:'user',SMTP_PASSWORD:'test-password',SMTP_FROM:'mail@example.com'}:{}),SIGS_EMAIL_ENABLED:String(enabled)};
const ctx={Deno:{env:{get:k=>settings[k]},serve:fn=>serve=fn},Response,renderEmail,nodemailer:{createTransport:opts=>{assert.equal(opts.secure,true);assert.equal(opts.port,465);return {verify:async()=>{},close(){},sendMail:async()=>{sends++;return {accepted:['recipient@example.com']};}};}},fetch:async(url,opts)=>{calls.push({url,opts});let data;if(url.endsWith('/auth/v1/user'))data={id:'real-user'};else if(url.includes('/profiles?'))data=[profile];else if(url.endsWith('/sigs_email_claim'))data=[{id:'job-id',lease_id:'lease',event:'license_activated',recipient:'recipient@example.com',payload:{company:'Company'}}];else if(url.endsWith('/sigs_email_complete'))data=true;return new Response(JSON.stringify(data));}};
vm.runInNewContext(source,ctx);return {invoke:async(action,token='user-token')=>serve(new Request('https://example.com',{method:'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},body:JSON.stringify({action})})),calls,get sends(){return sends;}};}
const denied=worker({profile:{role:'ADMIN',active:true}});assert.equal((await denied.invoke('dispatch')).status,403);assert.equal(denied.sends,0);assert.equal((await denied.invoke('dispatch','')).status,401);
const disabled=worker({enabled:false});assert.equal((await disabled.invoke('dispatch')).status,503);assert.equal(disabled.sends,0);assert.ok(!disabled.calls.some(c=>c.url.endsWith('sigs_email_claim')));
const missing=worker({configured:false});assert.equal((await missing.invoke('status')).status,200);assert.equal((await missing.invoke('verify')).status,503);assert.equal(missing.sends,0);
const valid=worker();assert.deepEqual(await (await valid.invoke('verify')).json(),{verified:true});assert.equal(valid.sends,0);assert.deepEqual(await (await valid.invoke('dispatch')).json(),{sent:1,failed:0,unknown:0});assert.equal(valid.sends,1);assert.ok(valid.calls.some(c=>c.url.endsWith('sigs_email_complete')));
console.log('PASS: verified user role, anonymous denial, disabled/unconfigured transport, verification without email and leased SMTP dispatch (mock transport).');
