const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
global.SIGSSiteGeometry=require('../assets/js/site-geometry-model-v28.js');global.SIGSProposalOptics=require('../assets/js/proposal-optics-v27.js');global.SIGSSceneModel=require('../assets/js/scene-model-v29.js');const M=require('../assets/js/engineering-model-v39.js');
assert.equal(M.bitrate(2,'uv_ultra265'),1);assert.equal(M.bitrate(4,'uv_ultra265'),M.bitrate(4,'ultra265b'));assert.equal(M.bitrate(8,'uv_ultra265max'),.8);assert.equal(M.bitrate(6,'h265'),6);assert.equal(M.bitrate(2,'h265',30),2.4);
const a=M.storage(2,'h265',1,{recordMbps:1});assert.equal(a.gb*2**30,10800000000);assert.equal(M.storage(2,'h265',1,{recordMbps:1,recordHours:12,recordDuty:50}).gb,a.gb/4);assert.equal(M.storage(2,'ultra265m',1,{recordMbps:1}).gb,a.gb);assert.equal(M.storage(2,'h265',1,{recordDuty:0}).gb,0);
assert.equal(M.diskCount(1000,1),2);assert.equal(M.displayStorage(1e12/2**30),'1.00 TB');
const p={x:0,y:0,instHeight:3,instTilt:15,rotation:0,lens:2.8,mp:4,label:'C1'},d={type:'bullet',fov:90,range:30,mp:4,resW:2688},f={scale:{ok:true,ppm:10},obstacles:[]},t={x:0,y:-100,height:1.6,name:'Entrada',goal:'r'};
let q=M.quality(p,d,f,t);assert(q.frame);assert(q.ppm>125);assert(q.passed);assert(!M.quality(p,d,f,{...t,goal:'i'}).passed);assert(M.quality({...p,lens:6},d,f,{...t,goal:'i'}).passed);assert(!M.quality(p,d,f,{...t,y:100}).passed);
const wall={height:4,points:[{x:-50,y:-50},{x:50,y:-50}]};assert(M.quality(p,d,{...f,obstacles:[wall]},t).blocked);assert(!M.quality(p,d,{...f,obstacles:[{...wall,height:1}]},t).blocked);assert(!M.quality(p,d,{...f,scale:{ok:false}},t).passed);assert.equal(M.widthPixels({...p,mp:2},d),1920);assert.equal(M.quality(p,{...d,type:'fisheye'},f,t).passed,false);
const u=M.ups(90,2,{poeEfficiency:1,nvrW:30,diskW:10,switchIdleW:10,powerFactor:.75,upsMinutes:30});assert.equal(u.load,150);assert.equal(u.watts,188);assert.equal(u.va,251);assert.equal(u.energyWh,75);assert.equal(M.ups(1000,10,{measuredLoad:100}).load,100);
// Execute the actual calculator with its rendered HTML and manual bitrate controls.
const {JSDOM}=require('jsdom');const dom=new JSDOM(fs.readFileSync(require.resolve('../app-Sigs.html'),'utf8'));
const e={window:null,document:dom.window.document,SIGSEngineeringModel:M,SIGSDiskModel:require('../assets/js/disk-model-v64.js'),console,setTimeout(){},Math};e.window=e;vm.createContext(e);const raw=fs.readFileSync(require.resolve('../assets/js/block-03.js'),'utf8');const start=raw.indexOf('var DC_BRANDS ='),end=raw.indexOf('function dcDrawGauge');vm.runInContext(raw.slice(start,end),e);e.dcDrawGauge=()=>{};e._dcBrand='uniview';e._dcCams=[{id:1,name:'Teste',resId:'2mp',codecId:'uv_ultra265',fps:25,qty:1}];const doc=e.document;for(const [id,val] of Object.entries({'dc-days':1,'dc-hours':24,'dc-margin':0,'dc-overhead':0,'dc-raid':0,'dc-record-mode':'continuous'}))doc.getElementById(id).value=val;e.dcCalc();assert(doc.getElementById('dc-s-raw').textContent.includes('21.6 GB'));assert(doc.getElementById('dc-s-margin').textContent.includes('21.6 GB'));
e._dcCams[0].bitrate=1;e._dcMotionOn=true;doc.getElementById('dc-motion-pct').value=100;doc.getElementById('dc-motion-factor').value=4;e.dcCalc();assert(doc.getElementById('dc-s-raw').textContent.includes('10.8 GB'),'Measured bitrate must not be multiplied by scene activity');
console.log('PASS: shared Ultra 265 scenarios, manual bitrate, FPS, hours/events, decimal disk capacity, zero margin, DORI framing/walls/resolution and UPS sizing.');
// Real engineering UI handlers: current floor is a cloned working copy, just like production.
const uiDoc=new JSDOM('<div class="studio-header-actions"></div>').window.document;
uiDoc.defaultView.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
const cp={...p,id:'cam01',libId:'cam',days:30,codec:'ultra265b'},uiFloor={...f,name:'Piso 0',placed:[JSON.parse(JSON.stringify(cp))]},history=[];
const ui={document:uiDoc,window:null,console,Math,Date,JSON,Set,SIGSEngineeringModel:M,SIGSRecommendationModel:require('../assets/js/recommendation-model-v24.js'),SIGSSceneModel:global.SIGSSceneModel,SIGSSiteGeometry:global.SIGSSiteGeometry,SIGSProposalOptics:global.SIGSProposalOptics,SIGS_COMMERCIAL:{},SIGS_V6:{currentStatus:'DRAFT'},MOD:'cctv',FLOORS:[uiFloor],FLOOR_CUR:0,S:{placed:[cp],scale:f.scale,tool:null},gD:()=>({...d,brand:'Uniview'}),fP:id=>ui.S.placed.find(x=>x.id===id),saveCurrentFloor(){ui.FLOORS[0].placed=JSON.parse(JSON.stringify(ui.S.placed));},sigsSystemRecommendation:()=>({warnings:[],nvr:{name:'NVR',ch:8,bw:80},disk:{qty:1,capacityTB:2},switch:{name:'PoE'}}),calcPoE:()=>({totalW:8,totalBW:4,totalWithMargin:10,requiredPorts:2,uplink:{design:5.2}}),calcStorage:M.storage,sigsV6MarkDirty(){ui.dirty=true;},notify(){},hint(){},uid:()=>String(Math.random()),pushUndo(){history.push(JSON.stringify(ui.S.placed));},cv:{style:{},addEventListener(){}},cw:{style:{}},ctx:{save(){},restore(){},beginPath(){},arc(){},fill(){},fillText(){}},w2s:(x,y)=>({x,y}),s2w:(x,y)=>({x,y}),ep:e=>e,onClick(){},onDown(){},onMove(){},render(){},setTool(){},switchFloor(){},startModule(){},_restoreProjectData(data){ui.S.placed=JSON.parse(JSON.stringify(data.placed));},SIGSGeometryTools:{cancel(){}},SIGSSceneTools:{cancel(){}},setTimeout(){},openPrintModal(){}};ui.window=ui;vm.createContext(ui);vm.runInContext(fs.readFileSync(require.resolve('../assets/js/engineering-v39.js'),'utf8'),ui);
ui.SIGSEngineering.open();let field=uiDoc.querySelector('[data-cam-setting$=":recordMbps"]');field.value='2.5';field.onchange();assert.equal(ui.S.placed[0].recordMbps,2.5);assert.equal(ui.FLOORS[0].placed[0].recordMbps,2.5);assert(ui.dirty);
uiDoc.getElementById('eng-zone').value='Porta <script>';uiDoc.getElementById('eng-goal').value='r';uiDoc.getElementById('eng-place').onclick();ui.onClick({button:0,x:0,y:-100});assert.equal(ui.S.placed[0].qualityTargets.length,1);assert.equal(ui.FLOORS[0].placed[0].qualityTargets.length,1);assert(!uiDoc.querySelector('script'));assert.equal(ui.SIGSEngineering.snapshot().zones.length,1);
const saved=JSON.parse(JSON.stringify({placed:ui.S.placed}));ui.S.placed[0].qualityTargets=[];ui._restoreProjectData(saved);ui.SIGSEngineering.open();assert.equal(ui.SIGSEngineering.snapshot().zones.length,1);
const thermalReport=fs.readFileSync(require.resolve('../assets/js/technical-report-v22.js'),'utf8');vm.runInContext(thermalReport,ui);const report=ui.SIGSTechnicalReport.markup({module:'cctv',project:'Teste',floors:[],engineering:ui.SIGSEngineering.snapshot()},{plans:false});assert(report.includes('Evidências de engenharia'));assert(report.includes('Porta &lt;script&gt;'));assert(report.includes('UPS'));assert(report.includes('Referências consultadas'));
ui.SIGS_V6.currentStatus='ARCHIVED';ui.SIGSEngineering.open();assert(uiDoc.getElementById('eng-place').disabled);const old=ui.S.placed[0].recordMbps;field=uiDoc.querySelector('[data-cam-setting$=":recordMbps"]');field.value='9';field.onchange();assert.equal(ui.S.placed[0].recordMbps,old);
console.log('PASS: real UI edits persist in working floor, zone placement, save/restore, escaped report evidence and archived-project guard.');
