const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../assets/js/lens-model-v45.js'),A=require('../assets/data/ajax-cctv-v47.js');
const ptz={id:'p',type:'ptz',name:'PTZ 2MP 33×',fov:58,range:40,color:'#3869e8'},fixed=A.rows.find(d=>d.focalLength===4),vf={id:'v',type:'bullet',lensMin:2.8,lensMax:12,name:'Varifocal',fov:100},other={id:'o',type:'bullet',lensMin:2.8,lensMax:13.5,name:'Motorizada'};
assert.equal(M.policy({type:'ptz',name:'Speed Dome 16× digital'}).zoom,null);assert.equal(M.policy(ptz).zoom,33);assert(!M.policy(ptz).label.includes('mm'));assert.equal(M.filterKey(ptz),'zoom:33');assert.equal(M.policy({type:'ptz',name:'Speed Dome',model:'X33'}).zoom,null,'Model digits must not manufacture zoom specs');assert.equal(M.policy({type:'ptz',name:'Speed Dome'}).adjustable,false);
assert(M.matches(fixed,'fixed','fixed:4'));assert(!M.matches(fixed,'varifocal',''));assert(!M.matches(vf,'varifocal','range:2.8:13.5'));assert(M.matches(other,'varifocal','range:2.8:13.5'));assert.equal(M.effective({lens:12},fixed),4);assert.equal(M.policy({type:'bullet',model:'CAM(4mm)'}).min,4);
const input={setAttribute(){}};M.syncControl(input,{lens:M.fromControl(33,ptz)},ptz);assert.equal(input.max,33);assert.equal(input.value,33);assert.equal(M.valueLabel({lens:M.fromControl(33,ptz)},ptz),'33×');assert(M.fov({lens:M.fromControl(33,ptz)},ptz)<M.fov({lens:M.fromControl(1,ptz)},ptz));
// Run actual sidebar installation/filter changes in a DOM, including module changes and remote replacement.
const {JSDOM}=require('jsdom'),dom=new JSDOM('<body><aside class="studio-rail"><div id="lp"><div id="lib-search-wrap"><input id="lib-search"></div><div id="dlist"></div><div id="ph-title"></div></div></aside>',{url:'https://example.org',runScripts:'outside-only'}),w=dom.window;
Object.assign(w,{S:{lib:[{...fixed,id:'f',brand:'ajax'},ptz,vf,other]},MOD:'cctv',SIGSLensModel:M,sLib(){},openCtxLib(){},requestAnimationFrame(){},setTimeout(fn){fn();},CLOUD:{}});
w.eval(fs.readFileSync('assets/js/sidebar-v13.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
const select=(id,value)=>{const n=w.document.getElementById(id);n.value=value;n.dispatchEvent(new w.Event('change'));};
select('s13-optic','fixed');select('s13-lens','fixed:4');assert.equal(w.document.querySelectorAll('.s13-device').length,1);assert(w.document.getElementById('dlist').textContent.includes('4 mm'));
select('s13-optic','ptz');select('s13-lens','zoom:33');assert.equal(w.document.querySelectorAll('.s13-device').length,1);assert(w.document.getElementById('dlist').textContent.includes('33×'));
select('s13-optic','varifocal');select('s13-lens','range:2.8:12');assert.equal(w.document.querySelectorAll('.s13-device').length,1);w.S.lib=[other];w.renderDevList();assert.equal(w.document.getElementById('s13-lens').value,'');assert.equal(w.document.querySelectorAll('.s13-device').length,1);w.MOD='alarm';w.renderDevList();assert(w.document.getElementById('s13-optic-wrap').hidden);dom.window.close();
// Execute production Canvas functions on real pixels: transparent hole, DORI and overlapping cameras.
const {createCanvas}=require('@napi-rs/canvas'),canvas=createCanvas(500,500),ctx=canvas.getContext('2d'),src=fs.readFileSync('assets/js/block-03.js','utf8');
function fn(name){let start=src.indexOf('function '+name+'('),end=src.indexOf('\n}',start)+2;return src.slice(start,end);}
const {ground}=require('../assets/js/optics-v13.js'),env={ctx,cv:canvas,MOD:'cctv',S:{scale:{ok:true,ppm:20},zoom:1},w2s:()=>({x:250,y:250}),sigsGroundGeometry:ground,lFOV:()=>60,lRange:()=>8,hr:()=> 'rgba(40,120,230,.4)',doriCalc:()=>({i:2,r:4,o:6,d:8}),SIGSImageProfile:()=> '2025',SIGSAdvancedModel:{distances:()=>Array.from({length:7},(_,i)=>({distance:i+1,color:'#88f',short:String(i)}))}};env.window=env;vm.createContext(env);for(const name of ['sigsClipBlind','drawCov','_drawSector','_drawRadarCov','_drawThermalBiCov'])vm.runInContext(fn(name),env);
const pixel=(x,y)=>[...ctx.getImageData(x,y,1,1).data],p={x:0,y:0,rotation:0,instHeight:3,instTilt:30,lens:2.8};
env.drawCov(p,ptz);assert.equal(pixel(250,240)[3],0,'Blind area has no fill or DORI');assert(pixel(250,150)[3]>0,'Coverage beyond blind distance is still visible');
ctx.clearRect(0,0,500,500);ctx.fillStyle='#f2eedd';ctx.fillRect(0,0,500,500);const before=pixel(250,240);env.drawCov(p,ptz);assert.deepEqual(pixel(250,240),before,'Plant/map background preserved');
ctx.fillStyle='rgba(230,20,30,.6)';ctx.fillRect(230,225,40,40);const overlap=pixel(250,240);env.drawCov(p,ptz);assert.deepEqual(pixel(250,240),overlap,'Earlier camera coverage preserved');
for(const type of ['radar','thermal_bi']){ctx.clearRect(0,0,500,500);env.drawCov(p,{...ptz,type,radarFov:60,radarRange:8,thermalFov:60,thermalRange:8,visibleFov:60,visibleRange:8});assert.equal(pixel(250,240)[3],0,type+' blind zone');}
const O=require('../assets/js/proposal-optics-v27.js');assert.equal(O.capture({...p,instTilt:45},ptz).instTilt,45);assert(O.sector({...p,type:'ptz',fov:60,range:8},20,[]).includes('clip-rule="evenodd"'));
console.log('PASS: PTZ 33×, real focal filters / DOM switching, fixed Ajax 4mm, actual canvas pixel transparency, DORI, map / camera overlap preservation, radar / thermal and proposal blind clipping.');
