const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<body class="sigs-premium"><aside class="studio-rail"><nav class="sigs-v5-nav"><div id="sigs-v5-report-menu">Relatório técnico</div><div id="present">Apresentar</div></nav><div class="studio-rail-foot"></div></aside><section id="lp"><div id="lib-search-wrap"><input id="lib-search"></div><div id="dlist"></div></section></body>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
const css=w.document.createElement('style');css.textContent=fs.readFileSync('assets/css/sidebar-v13.css','utf8');w.document.head.appendChild(css);
Object.defineProperty(w.document,'readyState',{value:'complete'});w.setTimeout=f=>f();w.requestAnimationFrame=f=>f();w.resize=()=>{};w.S={lib:[]};w.MOD='cctv';w.sLib=()=>{};w.CLOUD={user:{id:'u'}};w.SIGS_V6={dirty:false};let saves=[],loads=0,opened=[],resolveSave,notices=[];w.notify=s=>notices.push(s);w.sigsV6SaveProject=mode=>{saves.push(mode);return new Promise(r=>resolveSave=r);};w.openCloud=()=>{throw Error('Must not redirect to portal');};w.sigsV6ListProjects=async()=>{loads++;return [{id:'a',name:'Entrada <script>',module:'CCTV',status:'ACTIVE'},{id:'b',name:'Armazém',module:'FIRE',status:'DRAFT'}];};w.cloudOpenProject=async(id,name)=>{opened.push(id);return {id};};
vm.runInContext(fs.readFileSync('assets/js/sidebar-v13.js','utf8'),dom.getInternalVMContext());
const flush=()=>new Promise(r=>setImmediate(r));
(async()=>{
 const save=w.document.getElementById('s13-save-project'),load=w.document.getElementById('s13-load-project'),actions=save.parentElement;assert(save&&load);assert.equal(w.document.getElementById('sigs-v5-report-menu').nextElementSibling,actions);assert.equal(w.getComputedStyle(actions).display,'none','Actions only belong to Tools');
 w.document.querySelector('[data-sidebar-view="menu"]').click();assert.notEqual(w.getComputedStyle(actions).display,'none');assert.equal(save.getAttribute('aria-label'),'Guardar projeto');
 save.click();save.click();await Promise.resolve();assert.deepEqual(saves,['manual']);assert(save.disabled);resolveSave({id:'p'});await flush();assert(!save.disabled);
 load.click();await flush();assert.equal(loads,1);let panel=w.document.getElementById('s13-saved-projects');assert(panel);assert.equal(load.getAttribute('aria-expanded'),'true');assert.equal(panel.querySelectorAll('.s13-saved-project').length,2);assert(!panel.querySelector('script'));
 const search=panel.querySelector('input');search.value='Armaz';search.dispatchEvent(new w.Event('input'));assert.equal(panel.querySelectorAll('.s13-saved-project').length,1);panel.querySelector('.s13-saved-project').click();await flush();assert.deepEqual(opened,['b']);assert(!w.document.getElementById('s13-saved-projects'));
 w.document.getElementById('s13-collapse').click();load.click();await flush();assert.equal(w.document.querySelector('.studio-rail').dataset.collapsed,'false','Loading expands Tools to show projects');assert(w.document.getElementById('s13-saved-projects'));load.click();await flush();assert(!w.document.getElementById('s13-saved-projects'));
 w.sigsV6SaveProject=()=>Promise.reject(Error('Falha de rede'));save.click();await flush();assert.deepEqual(notices,['Falha de rede']);assert(!save.disabled);
 load.click();await flush();panel=w.document.getElementById('s13-saved-projects');w.SIGS_V6.dirty=true;w.confirm=()=>false;panel.querySelector('.s13-saved-project').click();await flush();assert.deepEqual(opened,['b']);assert(panel.isConnected);w.SIGS_V6.dirty=false;w.cloudOpenProject=async()=>null;panel.querySelector('.s13-saved-project').click();await flush();assert(panel.isConnected,'Failed load keeps the saved-project list open');
 panel.querySelector('button[aria-label]').click();assert(!w.document.getElementById('s13-saved-projects'));
 dom.window.close();console.log('PASS: Tools-only actions after report; inline saved list/search/load; no portal redirect; collapsed expansion; save failure recovery; dirty-load cancellation and failed-open preservation.');
})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close();});
