const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const T=require('../assets/data/thermal-cctv-v69.js'),Lens=require('../assets/js/lens-model-v45.js');
assert.equal(T.rows.length,12);assert.equal(T.rows.filter(d=>d.brand==='hikvision').length,6);assert.equal(T.rows.filter(d=>d.brand==='uniview').length,6);assert.equal(new Set(T.rows.map(T.key)).size,12);
for(const d of T.rows){assert.equal(d.type,'thermal_bi');assert.equal(d.family,'thermal');assert.equal(d.mp,4);assert.equal(d.resW,2688);assert(d.thermalResW<d.thermalStreamW,'Detector pixels must remain separate from upscaled stream');assert(d.thermalRange>0);assert(d.thermalFov>0&&d.thermalFov<180);assert(d.visibleFov>0&&d.visibleFov<180);assert.equal(d.range,d.visibleRange);assert.equal(d.fov,d.visibleFov);assert(d.poeW>0);assert(d.sourceURL.startsWith('https://'));assert.equal(Lens.policy(d).adjustable,false);assert.equal(Lens.effective({lens:100},d),d.visibleLens);assert(Lens.matches(d,'fixed',Lens.filterKey(d)));assert(T.label(d).includes(d.thermalResW+'×'+d.thermalResH));}
assert.equal(T.rows.find(d=>d.model==='DS-2TD2637-10/P').thermalRange,71,'Human VCA, not thermal DRI or temperature range');assert.equal(T.rows.find(d=>d.model==='DS-2TD2637-15/P').thermalRange,110);assert.equal(T.rows.find(d=>d.model==='TIC2624S-F35-4F12AC-I3').thermalRange,350);
const c={};vm.createContext(c);for(const p of ['equipment-catalog','ajax-cctv-v47','cctv-expansion-v52','visiotech-cctv-v53','visiotech-cctv-v54','thermal-cctv-v69'])vm.runInContext(fs.readFileSync('assets/data/'+p+'.js','utf8'),c);
assert.equal(c.CCTV_LIB.filter(d=>d.type==='thermal_bi').length,17);assert.deepEqual(T.merge(T.rows),T.merge(T.merge(T.rows)));
const d=T.rows[0],old={...d,id:'persisted-id',thermalFov:999};assert.equal(T.merge([old])[0].id,'persisted-id');assert.equal(T.merge([old])[0].thermalFov,d.thermalFov);assert.equal(T.merge([{...old,custom:true}])[0].thermalFov,999);
const source=fs.readFileSync('assets/js/catalog-supabase.js','utf8'),start=source.indexOf('  function productToDevice('),end=source.indexOf('  window.sigsCatalogLoadRemote=');
const runtime={SIGSThermalCatalog:T,MOD:'cctv',S:{lib:[{id:'custom',custom:true}]},clone:v=>JSON.parse(JSON.stringify(v)),renderDevList(){}};runtime.window=runtime;vm.createContext(runtime);vm.runInContext(source.slice(start,end),runtime);
runtime.applyRemote([{id:'remote-cam',reference:'OTHER',name:'Other model',category:'CCTV',family:'cctv',device_type:'bullet',specifications:{id:'other'},brand:{slug:'hikvision'}}]);assert.equal(runtime.CCTV_LIB.filter(d=>d.type==='thermal_bi').length,12);assert(runtime.S.lib.some(d=>d.id==='custom'));assert.equal(new Set(runtime.S.lib.map(d=>d.id)).size,runtime.S.lib.length);
const html=fs.readFileSync('app-Sigs.html','utf8');assert(html.indexOf('thermal-cctv-v69.js')<html.indexOf('block-03.js'));assert(html.indexOf('thermal-cctv-v69.js')<html.indexOf('catalog-supabase.js'));
// Exercise actual placement and both coverage cones for every model.
const block=fs.readFileSync('assets/js/block-03.js','utf8'),sectors=[];
const map={S:{placed:[],devN:0,scale:{ok:false,ppm:10},zoom:1},SIGSLensModel:Lens,sigsCatalogDeviceAllowed:()=>true,nextNum:()=>1,uid:()=>String(Math.random()),pushUndo(){},select(){},render(){},updateStats(){},hint(){},notify(){},sigsClipBlind(){},_drawSector:(ctx,radius,fov)=>sectors.push({radius,fov}),ctx:{save(){},restore(){},translate(){},rotate(){}}};vm.createContext(map);
vm.runInContext(block.slice(block.indexOf('function placeDevice('),block.indexOf('function hitT(')),map);vm.runInContext(block.slice(block.indexOf('function _drawThermalBiCov('),block.indexOf('function drawIcon(')),map);
for(const d of T.rows){map.S.activeLib=d;map.placeDevice(12,34);const p=map.S.placed.at(-1);assert.equal(p.libId,d.id);assert.equal(p.lens,d.visibleLens);assert(p.label.startsWith('THM'));sectors.length=0;map._drawThermalBiCov(p,d,{x:0,y:0});assert.deepEqual(sectors,[{radius:d.visibleRange*10,fov:d.visibleFov},{radius:d.thermalRange*10,fov:d.thermalFov}]);}
// The real sidebar exposes native resolution and keeps thermals in fixed-lens filters.
const {JSDOM}=require('jsdom');const dom=new JSDOM('<aside class="studio-rail"><nav class="sigs-v5-nav"></nav><div class="studio-rail-foot"></div></aside><section id="lp"><div id="lib-search-wrap"><input id="lib-search"></div><div id="dlist"></div></section>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
Object.defineProperty(w.document,'readyState',{value:'complete'});w.setTimeout=f=>f();w.requestAnimationFrame=f=>f();w.S={lib:T.rows};w.MOD='cctv';w.SIGSLensModel=Lens;w.SIGSThermalCatalog=T;w.sLib=()=>{};w.resize=()=>{};w.eval(fs.readFileSync('assets/js/sidebar-v13.js','utf8'));
assert.equal(w.document.querySelectorAll('.s13-device').length,12);assert(w.document.getElementById('dlist').textContent.includes('400×300'));const optic=w.document.getElementById('s13-optic');optic.value='fixed';optic.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.s13-device').length,12);const brand=w.document.getElementById('s13-brand');brand.value='uniview';brand.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.s13-device').length,6);dom.window.close();
console.log('PASS: 12 documented thermal models, native/stream resolution, sensor optics, human VCA ranges, fixed-lens filters, idempotent local/remote merge and stable saved/custom IDs');
