const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),M=require('../assets/js/workflow-model-v12.js'),V=require('../assets/js/quote-view-v12.js');
let seq=0;const id=()=>String(++seq);const catalog={};vm.runInNewContext(fs.readFileSync(path.join(root,'assets/data/equipment-catalog.js'),'utf8'),catalog);
for(const t of M.templates)for(const [module,lib] of [['cctv',catalog.CCTV_LIB],['alarm',catalog.AJAX_LIB],['fire',catalog.FIRE_LIB]]){const built=M.templateDevices(t,module,lib,id);assert.equal(built.missing.length,0,t.name+' '+module);assert.equal(built.placed.length,t[module].length);assert.equal(new Set(built.placed.map(d=>d.id)).size,built.placed.length);}
const floor={id:'f1',name:'Piso',placed:[{id:'d1',libId:'x',x:5,y:8}],meas:[{id:'m1'}],scale:{ok:true},fp:{storagePath:'private/path',imgData:'data:image/png;base64,AA',x:0,y:0,w:100,h:100}};
const copied=M.duplicateFloor(floor,id);assert.notEqual(copied.id,floor.id);assert.notEqual(copied.placed[0].id,floor.placed[0].id);copied.placed[0].x=99;assert.equal(floor.placed[0].x,5);assert.equal(copied.fp.storagePath,floor.fp.storagePath);
const q={lines:[{ref:'REF',name:'Camera',qty:2,unit:'un.',cost:50,costTotal:100,sale:80,net:160}],total:196.8,sub:160,iva:36.8,profit:60,missing:0};
const snap=M.publicSnapshot(q,{company:'Company',client:'Client',terms:'Terms',margin:30,logo:'javascript:alert(1)'},[floor],[{id:'x',model:'REF',name:'Camera'}],'Project');const json=JSON.stringify(snap);for(const secret of ['cost','profit','margin','storagePath','private/path'])assert.ok(!json.includes(secret),secret);assert.equal(snap.logo,'');
const malicious=M.clone(snap);malicious.project='<script>alert(1)</script>';malicious.lines[0].name='<img src=x onerror=alert(1)>';malicious.logo='javascript:alert(1)';malicious.floors[0].devices[0].x='1" onload="bad';const html=V.markup(malicious);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img src=x'));assert.ok(!html.includes('javascript:'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('onload='));
const changed=M.clone(snap);changed.lines[0].qty=3;changed.lines[0].sale=90;changed.total=270;assert.deepEqual(M.diff(snap,changed).map(x=>x.ref),['REF','Total']);
const csv=M.parseCSV('\ufeffReferência;Descrição;Custo;PVP;Stock;Imagem\r\nX;"Câmara; exterior";"1.234,56";"1499,90";5;https://example.com/a.png\r\n');const rows=M.importRows(csv,{reference:0,name:1,cost:2,pvp:3,stock:4,image:5});assert.equal(rows[0].cost,1234.56);assert.equal(M.decimal('1,234.56'),1234.56);assert.throws(()=>M.importRows(M.parseCSV('ref;cost\n__proto__;1'),{reference:0,cost:1}));assert.equal(rows[0].pvp,1499.9);assert.equal(rows[0].name,'Câmara; exterior');assert.throws(()=>M.parseCSV('a;b\n"x;y'));assert.throws(()=>M.importRows(M.parseCSV('ref;cost\nX;-1'),{reference:0,cost:1}));assert.throws(()=>M.importRows(M.parseCSV('ref;cost\nX;1\nX;2'),{reference:0,cost:1}));
const warnings=M.check({floors:[{name:'Piso',placed:[{libId:'cam',mp:8}],scale:{ok:false}}],lib:[{id:'cam',type:'dome'}],quote:{...q,missing:1,lines:[{ref:'NVR',type:'nvr',qty:1},{ref:'SW',type:'switch',qty:1},{ref:'HDD',type:'hdd',qty:3}]},nvrs:[{name:'NVR',ch:0,bw:10,maxMP:4,hdd:1}],switches:[{name:'SW',ports:0,budget:5}],bandwidth:30,maxMP:8,poe:20,maxItems:0,module:'cctv'});for(const expected of ['Escala por definir','Preços por completar','Canais do NVR','Banda do NVR','Resolução do NVR','Baias do NVR','Potência PoE','Portas PoE','Limite do plano'])assert.ok(warnings.some(x=>x.title===expected),expected);
for(const file of fs.readdirSync(path.join(root,'assets/js')).filter(f=>f.endsWith('.js')))new vm.Script(fs.readFileSync(path.join(root,'assets/js',file),'utf8'),{filename:file});for(const page of ['app-Sigs.html','proposta.html']){const html=fs.readFileSync(path.join(root,page),'utf8');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);for(const m of html.matchAll(/(?:src|href)="(assets\/[^"?]+)"/g))assert.ok(fs.existsSync(path.join(root,m[1])),m[1]);}
console.log('PASS: 12 installation templates, deep duplication, public privacy/XSS, commercial diffs, CSV validation, technical warnings and app/page syntax.');
